const common = require('./common.js');

const trinketArray = [
    [
        ['An Ork tooth. A string of numbers is etched into the enamel.',
         'A phial of soil from your home world.',
         'A bent spanner from a Hive World manufactorum.',
         'A small effigy of a Jokaero made from spare parts.',
         'A book of ribald poetry bound into the cover of a chronicle of Saint Julyana Gilead.',
         'Three pieces of dried alien fruit wrapped in wax paper.'],
        ['The hilt of a combat knife, the blade dissolved by acid.',
         'A canteen of rotgut brewed from corpse starches and thruster coolant.',
         'An icon of Saint Julyana Gilead covering her face as if weeping.',
         'A shard of wraithbone. When unobserved, the shard orients itself to point towards Ostia.',
         'The milky eye of an Astropath suspended in a vial of preservative fluid.',
         'A power cell incompatible with all known Imperium technology.'],
        ['A pack of thick Astra Militarum issue socks, never opened.',
         'A bottle of finest amasec brewed in Imperium Sanctus.',
         'A leather pouch containing '+dice(6)+' seeds.',
         'A book of confounding riddles with a blue and yellow cover and 81 pages.',
         'A boot polish tin containing '+dice(6)+' lho sticks.',
         'A necklace made of five regicide playing pieces on a silver chain.'],
        ['A doll in the form of a Space Marine made from an old shirt.',
         'A decagon carved roughly from bone with strange symbols on each face.',
         'A Data-Slate containing fragmentary maps of an ancient vessel lost in the Warp.',
         'A thick tome of the Imperial Creed, its cover sealed closed by an archaic lock.',
         'The ident tags of a long-dead soldier of the Astra Militarum.',
         'A counterfeit Administratum notary seal carved from a starchy tuber.'],
        ['A bucket of foul smelling red paint that cannot be washed off.',
         'A sheaf of Astra Militarum enlistment papers, never filled out.',
         'The severed finger of a Space Marine Power Fist, its markings inconsistent with any known Chapter.',
         'An ornate child\'s puzzle box. When solved, the box opens to reveal a disquieting symbol.',
         'A pict of a distant relation. Their face shows signs of subtle mutation.',
         'An Explorator\'s journal with strange plant clippings and insects pressed between the pages.'],
        ['A single card of the Emperor\'s Tarot bearing a name hastily written in blood.',
         'A magnetised piece of scrap metal showing an Ork glyph. It takes great force to remove the chit once attached.',
         'A copy of the Imperial Infantryman\'s Uplifting Primer. The book is bloodstained and charred from the impact of an energy weapon.',
         'An unread message from someone important to you.',
         'A fur hat made from the tufted crest of an Eldar Exarch\'s helmet.',
         'A pilgrim\'s token from Holy Terra.']
    ],
    [
        ['A cheap copy of a Ministorum seal made from moulded resin covered in a patina of metal.',
         'A polymorphine ampoule jury-rigged to hold a preserved blood sample.',
         'The dedication plaque of a Dauntless-class Light Cruiser thought lost during the Gilead Crusade.',
         'A faint vox-recording of a parent\'s last words.',
         'A page torn from a sacred text of the Imperial Creed bearing a black smudge in the centre.',
         'A diadem from a feudal world, its perimeter decorated with xenos claws.'],
        ['An antique Chrono that always runs fifteen minutes fast.',
         'A jawbone, supposedly from a saint, with High Gothic script worked into its surface in delicate scrimshaw.',
         'An unfired Bolt round, initials carved into its surface.',
         'A necklace of Imperial coins from various worlds strung on silver wire. The coins are worth just enough to pay for a funeral.',
         'A wind instrument made from meteoric iron that requires six fingers on each hand to play properly.',
         'A purity seal stamped with a grinning skull.'],
        ['A book of dirty Limericks and bawdy verse written in Low Gothic.',
         'A sealed translucent box containing a metallic liquid. The liquid splits and moves to avoid your direct gaze.',
         'A tiny servitor made from the remains of an avian believed native to Holy Terra. It sings sweetly, never repeating a tune.',
         'A gauzy crimson sash woven from mono-fibre once used to garrotte a treasonous Sub-Sector governor.',
         'A marble hand broken off an Imperial monument, its surface stained with Ork blood.',
         'Three corroded, magnetised ball bearings. Each is engraved with markings mimicking the continents of alien worlds.'],
        ['A lighter in the shape of a compact laspistol. Pulling the trigger produces a tiny, steady chemical flame from the barrel.',
         'A sheaf of grave rubbings taken from multiple headstones bearing the same name but different dates of birth and death',
         'A shard of stained glass from a fallen cathedral.',
         'The spent power cell of a T\'au Pulse Pistol.',
         'The command codes for a highly specific class of Cherub Servitors.',
         'A signet ring bearing the seal of a Nethreun Questor Imperialis unheard of since the opening of the Great Rift.'],
        ['A battered Astra Militarum survival kit. Its contents spent except for three water purification tablets.',
         'A crystal bottle of intoxicating perfume made from gyrinx musk glands.',
         'A tattered flag showing an Ork emblem of infamous Freebooter Kaptin Mag Galluz.',
         'A sealed bottle of red corrective ink bearing the label of the Adeptus Administratum.',
         'A braided lock of synthetic hair.',
         'A signed second volume of the memoirs of an Imperial hero.'],
        ['A burned-out memetic coil from a Servitor Skull.',
         'Sealed orders meant for a long-dead Lord Marshal of the Gilead Gravediggers.',
         'A battle damaged ID chip from a T\'au Fire Warrior.',
         'A stale wafer of hard tack from a Militarum commissary, thick enough to stop a slug round — as the dent in it may prove.',
         'A diamantine tuning fork engraved with the seal of a Choir Master of the Adeptus Ministorum.',
         'A deck of playing cards. Each card bears the image of an enemy of the Imperium.']
    ],
    [
        ['A vox recording of haunting xenos music from a species long thought extinct.',
         'A death mask in the image of a Canoness of the Adepta Sororitas.',
         'A reliquary containing a shard of gleaming ice. The ice never melts.',
         'A wafer-thin sheet of wraithbone covered in interconnected Aeldari glyphs.',
         'An improvised pendulum made from a length of optic cable and an autogun slug.',
         'A portable Auto-Quill modified to print Ork glyphs.'],
        ['A shrill whistle carved from a preserved horn.',
         'An Imperial noble\'s commissioning scroll, signed and notarised, dated in M43.',
         'A rockcrete brick pried from the defensive wall of a fallen Imperial bastion.',
         'A forged promissory note from the Upstanding Starch Guild on Gilead Primus.',
         'A ring of keys, each one encoded to a stasis vault on a different world.',
         'A list of seemingly unrelated machine components written in blocky, crabbed handwriting.'],
        ['An ornate silver snuffbox. The snuff within is fortified with trace amounts of xenos pollen.',
         'A fetish carved from volcanic glass depicting a skull-faced god sitting on a gothic throne.',
         'A ticket stub for a performance of an opera proscribed by the Ecclesiarchy.',
         'A dog-eared, lavishly illustrated children\'s primer of Imperial history.',
         'A classified document, redacted so that every word is blacked out except for one. It could read "crucible" or "cubicle".',
         'Coded data-slate of a significant Human bloodline showing possible mutation and xenos gene-grafting.'],
        ['A notched hourglass filled with the ruddy sand of Mars.',
         'Half of a shattered mask depicting a face distorted with fear.',
         'A smooth river stone with an Aeldari glyph carved into its surface.',
         'An eight-spoked cogwheel.',
         'A small triptych of the God-Emperor ascendant, martyred, and interred upon the Golden Throne. The hinges are rusted shut.',
         'The remote detonator to a Penal Legionnaire\'s explosive collar.'],
        ['A xenohide pouch containing the mummified heart of an unknown organism.',
         'A radiation-damaged design template for a plasma reactor with a single fatal design flaw.',
         'An exhaustive phrase book translating common phrases between multiple dialects of Low Gothic.',
         'The knob from the end of a Weirdboy\'s channelling rod.',
         'A clockwork replica of an attack bike that sparks and runs in circles when wound.',
         'A sash made from the interlocking scales of a Maiden World reptile.'],
        ['An illuminated book of hours. Many of the prayers within are edited in red ink.',
         'A prism-like mirror shard. Staring at one\'s own reflection in the shard causes vivid hallucinations.',
         'A piece of ceramite marked with the emblem of the Absolvers Chapter.',
         'Several lengths of ribbed cable meant to be worn around the head and neck, giving the wearer the appearance of possessing several high-quality augmetics.',
         'A bottle of sacramental wine blessed by Arch-Deacon Merramar Clade.',
         'A cheap replica of an Arbitrator\'s badge of office.']
    ]	
]; 


const trinket = function trinket() { 
    const chart = common.dice(3);
    const trinketRollOne = common.dice(6);
    const trinketRollTwo = common.dice(6);
    output = [
        'Trinket ('+chart+':'+trinketRollOne.toString()+trinketRollTwo.toString()+')',
        '*'+trinketArray[chart-1][trinketRollOne-1][trinketRollTwo-1]+'*'
    ]
    return output.join('/r');
}

module.exports = trinket;